// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK9oFwzMi4Mf_YVaNzTd1qHx4YdN41tZU',
    appId: '1:608948989587:web:410b90cad96b6bcdee2766',
    messagingSenderId: '608948989587',
    projectId: 'todolist-b02-24',
    authDomain: 'todolist-b02-24.firebaseapp.com',
    storageBucket: 'todolist-b02-24.firebasestorage.app',
    measurementId: 'G-254J5DZGK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgZiM7BORPuqEG85BvDqHu5tNaxGheLYM',
    appId: '1:608948989587:android:1e0928f1b7582518ee2766',
    messagingSenderId: '608948989587',
    projectId: 'todolist-b02-24',
    storageBucket: 'todolist-b02-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6VfGj94lknJ9DnPLWK0rOfM-fO5ZeNaI',
    appId: '1:608948989587:ios:5e8a9d65cd380dcbee2766',
    messagingSenderId: '608948989587',
    projectId: 'todolist-b02-24',
    storageBucket: 'todolist-b02-24.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );
}
